Swagger Page and auto-API-documentation-update
nightingaleproject/Reference-NCHS-API pull request #33
Opened 2022-10-14 18:16 UTC by RobertScalfani

This PR deploys a Swagger API Page as well as auto-updates the documentation whenever a relevant change is made.

2022-10-18 20:33 UTC, smacadam commented on swagger/v1/swagger.yaml
> +  version: v1
Change to the current version of the API v1.1.0-preview5

2022-10-19 21:44 UTC, pkmitre commented on messaging/Startup.cs
> +            app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "NVSSMessaging v1"));
I think we may not want swagger on the production deployments, can we not generate the JSON config file with swagger available in dev only?

2022-10-19 21:45 UTC, pkmitre requested changes

2022-10-19 21:45 UTC, pkmitre commented on messaging/Startup.cs
> +            app.UseSwaggerUI(c => c.SwaggerEndpoint("/swagger/v1/swagger.json", "NVSSMessaging v1"));
I think we may not want swagger on the production deployments, can we not generate the JSON config file with swagger available in dev only?

2022-10-20 00:58 UTC, pkmitre approved these changes

2022-10-20 00:58 UTC, merged